### ISSUE TITLE
`.php_cs` in the folder of the target file is not recognized

### ISSUE THREAD

**Issue by gh640** [adael/SublimePhpCsFixer#11]
I expected this package use the `.php_cs` if I don't specify the `config` in the settings but it doesn't.

`php-cs-fixer` by default uses `.php_cs` in the directory of the target file and I'd like to use that feature with this ST package.

**Comment by ComaVN** [comment]
You can specify a path relative to the project's directory in your config, so different projects have different formatting rules. Does that help?

eg. `"config": "${folder}/.php_cs"`

**Comment by adael** [comment]
I'm unsure if it would be a good idea to automatically use this .php_cs file, because it would make some undesired side effects if you're not aware of this functionality.

Furthermore I would rather than creating the temporary file in the same working directory, try to find if there's a ".php_cs" file in the same directory of the file that we're formatting and pass its path as config file if no other is passed. I think it's not a good idea to create temporary file in the same directory where is your code :stuck_out_tongue_winking_eye: 

Regards,

**Comment by gh640** [comment]
Thank you for your responses :)

@ComaVN:

> You can specify a path relative to the project's directory in your config, so different projects have different formatting rules. Does that help?

Yes, it works. But if there're several projects in Sublime Text 3, the variable `${folder}` seems to point only the first project in my environment. So when I need to handle several projects at a time and want to use this package with files in a project other than the first one, It doesn't work (if I understand it correctly). That's the reason why I wanted to introduce the original behavior of `php-cs-fixer` (if I understand it correctly). 

@adael: 

> I'm unsure if it would be a good idea to automatically use this .php_cs file, because it would make some undesired side effects if you're not aware of this functionality.

Oh, I see.. It's by design, right.

> Furthermore I would rather than creating the temporary file in the same working directory, try to find if there's a ".php_cs" file in the same directory of the file that we're formatting and pass its path as config file if no other is passed. I think it's not a good idea to create temporary file in the same directory where is your code

Yes, you're right. 

So, do you think if it's worth considering introducing the auto detection of `.php_cs` in the same directory if we don't create the temporary file in the directory where your code lie? Or, is the idea of the auto detection bad?

Thanks.

**Comment by ComaVN** [comment]
The [Sublime API](https://www.sublimetext.com/docs/3/api_reference.html)'s `extract_variables()` method returns quite a few other directories than just `${folder}`: `packages, platform, file, file_path, file_name, file_base_name, file_extension, folder, project, project_path, project_name, project_base_name, project_extension`. These are currently not replaced (simply because I didn't need them at the time), but maybe one of these can be used

Alternatively we could support `.` for the functionality you're after.

Marginally related: it would be nice to be able to pass a list of config locations instead of just one, and let php-cs-fixer use the first one that exists. I'll make a PR this weekend if you're interested.

**Comment by gh640** [comment]
@ComaVN Thank you. I see! In my case, `file_path` would work well. The directory of the target file would be one of the most frequently used pattern with this package and `.` also sounds good to me.

And I agree with you and interested in allowing a list format of `config`.

**Comment by ComaVN** [comment]
I think this will be fixed by PR #15

**Comment by gh640** [comment]
@adael  I'd like you to check the PR #15 when you have a time 😃

**Comment by adael** [comment]
done, sorry for the delay

**Comment by gh640** [comment]
@adael thank you!
