### ISSUE TITLE
on_save won't auto save

### ISSUE THREAD

**Issue by ramakrishnamundru** [adael/SublimePhpCsFixer#14]
When using the `on_save` option, it formats on saving but won't save the changes.
So we have to save the file twice to fix the changes.
Is there a way to fix it?

**Comment by gh640** [comment]
As you may already know, It's an expected correct behavior because the hook `on_post_save` is used for that.

https://github.com/adael/SublimePhpCsFixer/blob/master/SublimePhpCsFixer.py#L196

> Is there a way to fix it?

I believe <code>sublime.set_timeout()</code> would be useful to save the file automatically after formatted. 

https://www.sublimetext.com/docs/3/api_reference.html

You can freely propose a new way with PR, I think :)

**Comment by ramakrishnamundru** [comment]
Hi, is there any specific reason for using `on_post_save` cause `on_pre_save` seems to work fine for me.
also as this is not async, it don't think it will cause any problems.

I'm glad to submit a PR with this fix, if it is OK, cause I don't know anything about python and sublime API.

**Comment by gh640** [comment]
Hi.

> also as this is not async, 

You're right. This is not async. I was seeing a different issue and project at the time and I made a mistake.

Regarding the reason for the `on_post_save` not `on_pre_save`, I'm sorry, actually I'm not a maintainer and try waiting for the maintainer's response.

**Comment by adael** [comment]
Totally my fault. I was not using on_save feature so I didn't notice the problem. Thank you for suggesting to use on_pre_save.

Solved in the last commit and tagged with 1.0.5.
Thank you
